### ISSUE TITLE
Double-pass Processing for Comprehensive Reporting

### ISSUE THREAD

**Issue by fosterbrereton** [adobe/orc#26]
Alter the processing algorithm to be two-pass:

1. Determine a set of symbols for which a conflict has been identified
2. Derive a comprehensive list of symbol definitions for all symbols found in pass 1

**Comment by leethomason** [comment]
(Capturing a conversation on this)
The current bug captured in the comment:
```
    // The number of unique ODRVs is tricky.
    // If A, B, and C are types, and C is different, then if we scan:
    // A, B, then C -> 1 ODRV, but C, then A, B -> 2 ODRVs. Complicating
    // this is that (as this comment is written) we don't detect supersets.
    // So if C has more methods than A and B it may not be detected.
```

At a high level the idea is two passes:
* one pass to find the path of each ODRV (which can come in any order)
* a second pass to find every DIE associated with that ODRV path

In more detail:

* Scan all the DIEs as we do now. Change: record paths that are ODRVs, but don't report.
* ORC has a complete set of DIEs. (We store them globally.). Each DIE and pool_string is now in immutable fixed memory that will last the life of the program.
* Going wide across cores, re-walk all the DIEs, look for matches to ODRV paths, store in matches in vectors. Store per thread so we don't lock. Start with a simple search to see if it works.
* New: Join vectors of conflicts on main thread (only a few thousand, should be fine). We now have a full list of ODR violating DIEs.
* New: Sort / filter the conflicts into a deterministic order
* Print!
