### ISSUE TITLE
Orc does not check the directory it is in for the config file

### ISSUE THREAD

**Issue by OmniTroid** [adobe/orc#9]
**Describe the bug**

The documentation states: "ORC will walk the current directory up, looking for a config file named either..". However, when a config file is placed in the same folder as the orc executable it does not find this config file. It does find it when placed in the parent directory, though.

**Expected behavior**

Given the formulation in the documentation, I would expect ORC to check the directory the executable is in first.

**Environment:**
 - OS: MacOS 10.15
 - Compiler/IDE: Ninja
 - Version: 0.0.1

**Comment by fosterbrereton** [comment]
Fixed with PR #10
